server:
  port: 8081

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/utn_phones
#    username: root
#    password:
#  jpa:
#    hibernate:
#      format_sql: true
#      ddl-auto: create-drop
#    show-sql: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true

