server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/utn_phones
    username: root
    password:
  jpa:
    hibernate:
      format_sql: true
    show-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true

